
require'keymap.barbar'
--require'keymap.completions'
require'keymap.fugitive'
require'keymap.global'
require'keymap.harpoon'
--require'keymap.lsp'
require'keymap.hop'
require'keymap.tabs'
require'keymap.telescope'
require'keymap.toggleterm'
require'keymap.trouble'
require'keymap.windows'
